export enum PostsAction {
  GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS",
  GET_POSTS_NOT_FOUND = "GET_POSTS_NOT_FOUND",
  GET_POSTS_HTTP_INTERNAL_ERROR = "GET_POSTS_HTTP_INTERNAL_ERROR",
  GET_POSTS_ERROR = "GET_POSTS_ERROR",

  GET_POST_SUCCESS = "GET_POST_SUCCESS",
  GET_POST_NOT_FOUND = "GET_POST_NOT_FOUND",
  GET_POST_HTTP_INTERNAL_ERROR = "GET_POST_HTTP_INTERNAL_ERROR",
  GET_POST_ERROR = "GET_POST_ERROR",

  CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS",
  CREATE_POSTS_NOT_FOUND = "CREATE_POSTS_NOT_FOUND",
  CREATE_POSTS_HTTP_INTERNAL_ERROR = "CREATE_POSTS_HTTP_INTERNAL_ERROR",
  CREATE_POSTS_ERROR = "CREATE_POSTS_ERROR",
}
