export enum PostsAction {
  GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS",
  GET_POSTS_NOT_FOUND = "GET_POSTS_NOT_FOUND",
  GET_POSTS_HTTP_INTERNAL_ERROR = "GET_POSTS_HTTP_INTERNAL_ERROR",
  GET_POSTS_ERROR = "GET_POSTS_ERROR",
}
