export enum UsersAction {
  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  GET_USER_NOT_FOUND = "GET_USER_NOT_FOUND",
  GET_USER_HTTP_INTERNAL_ERROR = "GET_USER_HTTP_INTERNAL_ERROR",
  GET_USER_ERROR = "GET_USER_ERROR",

  POST_USER_WORKSPACE_ACTIVE_SUCCESS = "POST_USER_WORKSPACE_ACTIVE_SUCCESS",
  POST_USER_WORKSPACE_ACTIVE_NOT_FOUND = "POST_USER_WORKSPACE_ACTIVE_NOT_FOUND",
  POST_USER_WORKSPACE_ACTIVE_HTTP_INTERNAL_ERROR = "POST_USER_WORKSPACE_ACTIVE_HTTP_INTERNAL_ERROR",
  POST_USER_WORKSPACE_ACTIVE_ERROR = "POST_USER_WORKSPACE_ACTIVE_ERROR",
}
