export enum SocialAccountsUseState {
  GET_SOCIAL_ACCOUNTS = "GET_SOCIAL_ACCOUNTS",
  GET_LINKEDIN_LOGIN_URL = "GET_LINKEDIN_LOGIN_URL",
  GET_FACEBOOK_LOGIN_URL = "GET_FACEBOOK_LOGIN_URL",
  GET_TWITTER_LOGIN_URL = "GET_TWITTER_LOGIN_URL",
}

export enum WorkspacesUseState {
  GET_WORKSPACES = "GET_WORKSPACES",
  GET_WORKSPACE = "GET_WORKSPACE",
}

export enum UsersUseState {
  GET_USER = "GET_USER",
  POST_USERS_WORKSPACE_ACTIVE = "POST_USERS_WORKSPACE_ACTIVE",
}

export enum PostsUseState {
  GET_POSTS = "GET_POSTS",
  GET_POST = "GET_POST",
}
